"""empty message

Revision ID: 8434093fb044
Revises: 
Create Date: 2024-02-15 22:23:50.828207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8434093fb044'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.BLOB(), nullable=False),
    sa.Column('thread', sa.String(length=40), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('from_station', sa.String(length=10), nullable=False),
    sa.Column('to_station', sa.String(length=10), nullable=False),
    sa.Column('salt', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_route')
    # ### end Alembic commands ###
